### ISSUE TITLE
Columns of IPv4 IPs don't sort

### ISSUE THREAD

**Issue by Science4583** [DanielHeath/sortable#1]
It doesn't sort columns that have IPv4 IPs.

|col1|col2|col3|
|---|---|---|
|Test1|1.0.0.1|Test1|
|Test2|1.0.0.2|Test2|

**Comment by Science4583** [comment]
I just discovered it also breaks Github markdown...

![image](https://user-images.githubusercontent.com/5973940/75123924-a6576b80-5679-11ea-9d57-71e5c193caf8.png)

![image](https://user-images.githubusercontent.com/5973940/75123926-abb4b600-5679-11ea-9376-92158c8b19a1.png)

**Comment by DanielHeath** [comment]
That is strange - want to take a look?

**Comment by Science4583** [comment]
I'm not a dev but I'll give it a shot. This plugin can't die!

**Comment by DanielHeath** [comment]
Also, when reporting an issue if you include a link to a publicly-accessible page I can test it on, that makes it easier for me to take a look.

**Comment by Science4583** [comment]
True. I assumed the table I made in the markdown here would have been an example. You know what happens when you assume; sometimes you're wrong.

**Comment by DanielHeath** [comment]
Oh wait, I thought that was a screenshot for some reason.

**Comment by DanielHeath** [comment]
New version is out!

**Comment by DanielHeath** [comment]
Also, the icon now looks like a sort icon.
